import АдиевРашид from "../assets/images/Адиев Рашид Абусат оглы.jpeg";
import БерстеневаАлена from "../assets/images/Берстенева Алена Викторовна.jpeg";
import БобокАлександр from "../assets/images/Бобок Александр Юрьевич.jpeg";
import БорбликМихаил from "../assets/images/Борблик Михаил Анатольевич.jpeg";
import ДмитриеваВероника from "../assets/images/Дмитриева Вероника Алексеевна.jpeg";
import ДуроваНаталья from "../assets/images/Дурова Наталья Юрьевна.jpeg";
import ЖаглинаЖанна from "../assets/images/Жаглина Жанна Маратовна.jpeg";
import КарагодинаМария from "../assets/images/Карагодина Мария Анатольевна.jpeg";
import КирееваЮлия from "../assets/images/Киреева Юлия Сергеевна.jpeg";
import КодоловаЕлена from "../assets/images/Кодолова Елена Аркадьевна.jpeg";
import КротковНиколай from "../assets/images/Кротков Николай Андреевич.jpeg";
import КузьменкоИгорь from "../assets/images/Кузьменко Игорь Владимирович1.jpeg";
import КунинаТатьяна from "../assets/images/Кунина Татьяна Сергеевна.jpeg";
import МитренкоАндрей from "../assets/images/Митренко Андрей Игоревич.jpeg";
import ОрловаЮлия from "../assets/images/Орлова Юлия Валериевна.jpeg";
import ПроскуринаЕлена from "../assets/images/Проскурина Елена Михайловна.jpeg";
import СавушкинаЭмма from "../assets/images/Савушкина Эмма Александровна.jpeg";
import СенотрусоваЮлия from "../assets/images/Сенотрусова Юлия Юрьевна.jpeg";
import СеркбаеваАлтын from "../assets/images/Серкбаева Алтын Суннатовна.jpeg";
import СорокинИлья from "../assets/images/Сорокин Илья Юрьевич.jpeg";
import ТихомироваМария from "../assets/images/Тихомирова Мария Алексеевна.jpeg";
import ТомсонЕкатерина from "../assets/images/Томсон Екатерина Андреевна.jpeg";
import ХасаншинаВенера from "../assets/images/Хасаншина Венера Хамитовна.jpeg";
import ЧернецВиктория from "../assets/images/Чернец Виктория Александровна.jpeg";
import ШаброваИрина from "../assets/images/Шаброва Ирина Сергеевна.jpeg";
import ШебановаОльга from "../assets/images/Шебанова Ольга Евгеньевна.jpeg";
import МакаровПавел from "../assets/images/Макаров Павел Сергеевич.jpeg";

export const news = {
  timePeriod: [
    {
      name: "сегодня",
      news: [
        {
          newsId: "news1",
          date: "19.12.22",
          tournamentId: "T3",
          newsText:
            "Новое достижение! Игорь и еще 32 участника заработали для банка по 3 млн.руб. от сделок с индийскими компаниями. Поздравляем ребят с крутым достижением! Дополнительно каждому выпущена награда в формате <a href='https://dfa.sber.ru/nft/tokens/view/2cDe52F4H3ixbxXeknmDWiEkopFNYV6WQ8oT1aTPutDAjWNJQGVxw8mKsiifqMALhF28vUqFHkxSHoejuiAHZd6iLef8D6u' style='text-decoration: underline'>NFT на платформе ЦФА Сбера</a>.",
          leaders: [
            {
              employeeNumber: "22",
              isMarked: true,
              firstName: "Игорь",
              lastName: "Кузьменко",
              photoData: КузьменкоИгорь,
              terDivisionName: "СРБ",
              placeInRating: 1,
              crystalsEarned: 120,
              indicatorValue: "",
              colorCode: {
                primary: "blue-60",
                secondary: "blue-30",
              },
            },
            {
              employeeNumber: "19",
              isMarked: false,
              firstName: "Алёна",
              lastName: "Берстенева",
              photoData: БерстеневаАлена,
              terDivisionName: "СИБ",
              placeInRating: 2,
              crystalsEarned: 119,
              indicatorValue: "",
              colorCode: {
                primary: "blue-60",
                secondary: "blue-30",
              },
            },
            {
              employeeNumber: "3",
              isMarked: false,
              firstName: "Руфина",
              lastName: "Черняк",
              photoData: "",
              terDivisionName: "ББ",
              placeInRating: 3,
              crystalsEarned: 115,
              indicatorValue: "",
              colorCode: {
                primary: "blue-60",
                secondary: "blue-30",
              },
            },
            {
              employeeNumber: "28",
              isMarked: false,
              firstName: "Наталья",
              lastName: "Дурова",
              photoData: ДуроваНаталья,
              terDivisionName: "ЦЧБ",
              placeInRating: 4,
              crystalsEarned: 114,
              indicatorValue: "",
              colorCode: {
                primary: "blue-60",
                secondary: "blue-30",
              },
            },
            {
              employeeNumber: "14",
              isMarked: false,
              firstName: "Юлия",
              lastName: "Орлова",
              photoData: ОрловаЮлия,
              terDivisionName: "ПБ",
              placeInRating: 5,
              crystalsEarned: 112,
              indicatorValue: "",
              colorCode: {
                primary: "blue-60",
                secondary: "blue-30",
              },
            },
            {
              employeeNumber: "25",
              isMarked: false,
              firstName: "Алтын",
              lastName: "Серкбаева",
              photoData: СеркбаеваАлтын,
              terDivisionName: "УБ",
              placeInRating: 6,
              crystalsEarned: 108,
              indicatorValue: "",
              colorCode: {
                primary: "blue-60",
                secondary: "blue-30",
              },
            },
            {
              employeeNumber: "32",
              isMarked: false,
              firstName: "Михаил",
              lastName: "Борблик",
              photoData: БорбликМихаил,
              terDivisionName: "ЮЗБ",
              placeInRating: 7,
              crystalsEarned: 100,
              indicatorValue: "",
              colorCode: {
                primary: "blue-60",
                secondary: "blue-30",
              },
            },
            {
              employeeNumber: "18",
              isMarked: false,
              firstName: "Эмма",
              lastName: "Савушкина",
              photoData: СавушкинаЭмма,
              terDivisionName: "СЗБ",
              placeInRating: 8,
              crystalsEarned: 98,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "13",
              isMarked: false,
              firstName: "Мария",
              lastName: "Карагодина",
              photoData: КарагодинаМария,
              terDivisionName: "СИБ",
              placeInRating: 9,
              crystalsEarned: 98,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "1",
              isMarked: false,
              firstName: "Павел",
              lastName: "Макаров",
              photoData: МакаровПавел,
              terDivisionName: "ББ",
              placeInRating: 10,
              crystalsEarned: 94,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "21",
              isMarked: false,
              firstName: "Екатерина",
              lastName: "Томсон",
              photoData: ТомсонЕкатерина,
              terDivisionName: "СИБ",
              placeInRating: 11,
              crystalsEarned: 93,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "24",
              isMarked: false,
              firstName: "Ирина",
              lastName: "Шаброва",
              photoData: ШаброваИрина,
              terDivisionName: "СИБ",
              placeInRating: 12,
              crystalsEarned: 87,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "15",
              isMarked: false,
              firstName: "Татьяна",
              lastName: "Кунина",
              photoData: КунинаТатьяна,
              terDivisionName: "ПБ",
              placeInRating: 13,
              crystalsEarned: 85,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "8",
              isMarked: false,
              firstName: "Илья",
              lastName: "Сорокин",
              photoData: СорокинИлья,
              terDivisionName: "ДВБ",
              placeInRating: 14,
              crystalsEarned: 85,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "2",
              isMarked: false,
              firstName: "Елена",
              lastName: "Проскурина",
              photoData: ПроскуринаЕлена,
              terDivisionName: "ББ",
              placeInRating: 15,
              crystalsEarned: 84,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "26",
              isMarked: false,
              firstName: "Николай",
              lastName: "Кротков",
              photoData: КротковНиколай,
              terDivisionName: "УБ",
              placeInRating: 16,
              crystalsEarned: 83,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "33",
              isMarked: false,
              firstName: "Виктория",
              lastName: "Чернец",
              photoData: ЧернецВиктория,
              terDivisionName: "ЮЗБ",
              placeInRating: 17,
              crystalsEarned: 81,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "16",
              isMarked: false,
              firstName: "Александр",
              lastName: "Захаров",
              photoData: "",
              terDivisionName: "СЗБ",
              placeInRating: 18,
              crystalsEarned: 76,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "29",
              isMarked: false,
              firstName: "Юлия",
              lastName: "Киреева",
              photoData: КирееваЮлия,
              terDivisionName: "ЦЧБ",
              placeInRating: 19,
              crystalsEarned: 76,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "5",
              isMarked: false,
              firstName: "Венера",
              lastName: "Хасаншина",
              photoData: ХасаншинаВенера,
              terDivisionName: "ВВБ",
              placeInRating: 20,
              crystalsEarned: 75,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "30",
              isMarked: false,
              firstName: "Жанна",
              lastName: "Жаглина",
              photoData: ЖаглинаЖанна,
              terDivisionName: "ЦЧБ",
              placeInRating: 21,
              crystalsEarned: 66,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "4",
              isMarked: false,
              firstName: "Елена",
              lastName: "Проскурина",
              photoData: ПроскуринаЕлена,
              terDivisionName: "ВВБ",
              placeInRating: 22,
              crystalsEarned: 62,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "9",
              isMarked: false,
              firstName: "Юлия",
              lastName: "Сенотрусова",
              photoData: СенотрусоваЮлия,
              terDivisionName: "ДВБ",
              placeInRating: 23,
              crystalsEarned: 62,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "10",
              isMarked: false,
              firstName: "Вероника",
              lastName: "Дмитриева",
              photoData: ДмитриеваВероника,
              terDivisionName: "МБ",
              placeInRating: 24,
              crystalsEarned: 61,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "11",
              isMarked: false,
              firstName: "Ярослав",
              lastName: "Митосев",
              photoData: "",
              terDivisionName: "МБ",
              placeInRating: 25,
              crystalsEarned: 55,
              indicatorValue: "",
              colorCode: {
                primary: "orange-60",
                secondary: "orange-30",
              },
            },
            {
              employeeNumber: "31",
              isMarked: false,
              firstName: "Ольга",
              lastName: "Шебанова",
              photoData: ШебановаОльга,
              terDivisionName: "ЮЗБ",
              placeInRating: 26,
              crystalsEarned: 48,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
            {
              employeeNumber: "17",
              isMarked: false,
              firstName: "Марина",
              lastName: "Сорокина",
              photoData: "",
              terDivisionName: "СЗБ",
              placeInRating: 27,
              crystalsEarned: 48,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
            {
              employeeNumber: "6",
              isMarked: false,
              firstName: "Елена",
              lastName: "Кодолова",
              photoData: КодоловаЕлена,
              terDivisionName: "ВВБ",
              placeInRating: 28,
              crystalsEarned: 43,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
            {
              employeeNumber: "7",
              isMarked: false,
              firstName: "Андрей",
              lastName: "Митренко",
              photoData: МитренкоАндрей,
              terDivisionName: "ДВБ",
              placeInRating: 29,
              crystalsEarned: 42,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
            {
              employeeNumber: "27",
              isMarked: false,
              firstName: "Мария",
              lastName: "Брусницына",
              photoData: "",
              terDivisionName: "УБ",
              placeInRating: 30,
              crystalsEarned: 42,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
            {
              employeeNumber: "20",
              isMarked: false,
              firstName: "Рашид",
              lastName: "Адиев",
              photoData: АдиевРашид,
              terDivisionName: "СИБ",
              placeInRating: 31,
              crystalsEarned: 40,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
            {
              employeeNumber: "23",
              isMarked: false,
              firstName: "Мария",
              lastName: "Тихомирова",
              photoData: ТихомироваМария,
              terDivisionName: "СРБ",
              placeInRating: 32,
              crystalsEarned: 25,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
            {
              employeeNumber: "12",
              isMarked: false,
              firstName: "Александр",
              lastName: "Бобок",
              photoData: БобокАлександр,
              terDivisionName: "МБ",
              placeInRating: 33,
              crystalsEarned: 11,
              indicatorValue: "",
              colorCode: {
                primary: "light-green-30",
                secondary: "light-green-20",
              },
            },
          ],
        },
      ],
    },
  ],
};

export const newsId = {
  newsId: "news1",
  date: "19 декабря 2022",
  tournamentId: "",
  newsText:
    "Новое достижение! Игорь и еще 32 участника заработали для банка по 3 млн.руб. от сделок с индийскими компаниями. Поздравляем ребят с крутым достижением! Дополнительно каждому выпущена награда в формате <a href='https://dfa.sber.ru/nft/tokens/view/2cDe52F4H3ixbxXeknmDWiEkopFNYV6WQ8oT1aTPutDAjWNJQGVxw8mKsiifqMALhF28vUqFHkxSHoejuiAHZd6iLef8D6u' style='text-decoration: underline'>NFT на платформе ЦФА Сбера</a>.",
  leaders: [
    {
      employeeNumber: "22",
      isMarked: true,
      firstName: "Игорь",
      lastName: "Кузьменко",
      photoData: КузьменкоИгорь,
      terDivisionName: "СРБ",
      placeInRating: 1,
      crystalsEarned: 120,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "19",
      isMarked: false,
      firstName: "Алёна",
      lastName: "Берстенева",
      photoData: БерстеневаАлена,
      terDivisionName: "СИБ",
      placeInRating: 2,
      crystalsEarned: 119,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "3",
      isMarked: false,
      firstName: "Руфина",
      lastName: "Черняк",
      photoData: "",
      terDivisionName: "ББ",
      placeInRating: 3,
      crystalsEarned: 115,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "28",
      isMarked: false,
      firstName: "Наталья",
      lastName: "Дурова",
      photoData: ДуроваНаталья,
      terDivisionName: "ЦЧБ",
      placeInRating: 4,
      crystalsEarned: 114,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "14",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Орлова",
      photoData: ОрловаЮлия,
      terDivisionName: "ПБ",
      placeInRating: 5,
      crystalsEarned: 112,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "25",
      isMarked: false,
      firstName: "Алтын",
      lastName: "Серкбаева",
      photoData: СеркбаеваАлтын,
      terDivisionName: "УБ",
      placeInRating: 6,
      crystalsEarned: 108,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "32",
      isMarked: false,
      firstName: "Михаил",
      lastName: "Борблик",
      photoData: БорбликМихаил,
      terDivisionName: "ЮЗБ",
      placeInRating: 7,
      crystalsEarned: 100,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "18",
      isMarked: false,
      firstName: "Эмма",
      lastName: "Савушкина",
      photoData: СавушкинаЭмма,
      terDivisionName: "СЗБ",
      placeInRating: 8,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "13",
      isMarked: false,
      firstName: "Мария",
      lastName: "Карагодина",
      photoData: КарагодинаМария,
      terDivisionName: "СИБ",
      placeInRating: 9,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "1",
      isMarked: false,
      firstName: "Павел",
      lastName: "Макаров",
      photoData: МакаровПавел,
      terDivisionName: "ББ",
      placeInRating: 10,
      crystalsEarned: 94,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "21",
      isMarked: false,
      firstName: "Екатерина",
      lastName: "Томсон",
      photoData: ТомсонЕкатерина,
      terDivisionName: "СИБ",
      placeInRating: 11,
      crystalsEarned: 93,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 12,
      crystalsEarned: 87,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "15",
      isMarked: false,
      firstName: "Татьяна",
      lastName: "Кунина",
      photoData: КунинаТатьяна,
      terDivisionName: "ПБ",
      placeInRating: 13,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "8",
      isMarked: false,
      firstName: "Илья",
      lastName: "Сорокин",
      photoData: СорокинИлья,
      terDivisionName: "ДВБ",
      placeInRating: 14,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "2",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ББ",
      placeInRating: 15,
      crystalsEarned: 84,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "26",
      isMarked: false,
      firstName: "Николай",
      lastName: "Кротков",
      photoData: КротковНиколай,
      terDivisionName: "УБ",
      placeInRating: 16,
      crystalsEarned: 83,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "33",
      isMarked: false,
      firstName: "Виктория",
      lastName: "Чернец",
      photoData: ЧернецВиктория,
      terDivisionName: "ЮЗБ",
      placeInRating: 17,
      crystalsEarned: 81,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "16",
      isMarked: false,
      firstName: "Александр",
      lastName: "Захаров",
      photoData: "",
      terDivisionName: "СЗБ",
      placeInRating: 18,
      crystalsEarned: 76,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "29",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Киреева",
      photoData: КирееваЮлия,
      terDivisionName: "ЦЧБ",
      placeInRating: 19,
      crystalsEarned: 76,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "5",
      isMarked: false,
      firstName: "Венера",
      lastName: "Хасаншина",
      photoData: ХасаншинаВенера,
      terDivisionName: "ВВБ",
      placeInRating: 20,
      crystalsEarned: 75,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "30",
      isMarked: false,
      firstName: "Жанна",
      lastName: "Жаглина",
      photoData: ЖаглинаЖанна,
      terDivisionName: "ЦЧБ",
      placeInRating: 21,
      crystalsEarned: 66,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "4",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ВВБ",
      placeInRating: 22,
      crystalsEarned: 62,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "9",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Сенотрусова",
      photoData: СенотрусоваЮлия,
      terDivisionName: "ДВБ",
      placeInRating: 23,
      crystalsEarned: 62,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "10",
      isMarked: false,
      firstName: "Вероника",
      lastName: "Дмитриева",
      photoData: ДмитриеваВероника,
      terDivisionName: "МБ",
      placeInRating: 24,
      crystalsEarned: 61,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "11",
      isMarked: false,
      firstName: "Ярослав",
      lastName: "Митосев",
      photoData: "",
      terDivisionName: "МБ",
      placeInRating: 25,
      crystalsEarned: 55,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "31",
      isMarked: false,
      firstName: "Ольга",
      lastName: "Шебанова",
      photoData: ШебановаОльга,
      terDivisionName: "ЮЗБ",
      placeInRating: 26,
      crystalsEarned: 48,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      employeeNumber: "17",
      isMarked: false,
      firstName: "Марина",
      lastName: "Сорокина",
      photoData: "",
      terDivisionName: "СЗБ",
      placeInRating: 27,
      crystalsEarned: 48,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      employeeNumber: "6",
      isMarked: false,
      firstName: "Елена",
      lastName: "Кодолова",
      photoData: КодоловаЕлена,
      terDivisionName: "ВВБ",
      placeInRating: 28,
      crystalsEarned: 43,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      employeeNumber: "7",
      isMarked: false,
      firstName: "Андрей",
      lastName: "Митренко",
      photoData: МитренкоАндрей,
      terDivisionName: "ДВБ",
      placeInRating: 29,
      crystalsEarned: 42,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      employeeNumber: "27",
      isMarked: false,
      firstName: "Мария",
      lastName: "Брусницына",
      photoData: "",
      terDivisionName: "УБ",
      placeInRating: 30,
      crystalsEarned: 42,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      employeeNumber: "20",
      isMarked: false,
      firstName: "Рашид",
      lastName: "Адиев",
      photoData: АдиевРашид,
      terDivisionName: "СИБ",
      placeInRating: 31,
      crystalsEarned: 40,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      employeeNumber: "23",
      isMarked: false,
      firstName: "Мария",
      lastName: "Тихомирова",
      photoData: ТихомироваМария,
      terDivisionName: "СРБ",
      placeInRating: 32,
      crystalsEarned: 25,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      employeeNumber: "12",
      isMarked: false,
      firstName: "Александр",
      lastName: "Бобок",
      photoData: БобокАлександр,
      terDivisionName: "МБ",
      placeInRating: 33,
      crystalsEarned: 11,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
  ],
};

export const newsRatingCountry = {
  heading: "Игорь Кузьменко из СРБ на 1 месте!",
  usersPosition: "Вы на 1 из 33 месте",
  leaders: [
    {
      employeeNumber: "22",
      firstName: "Игорь",
      lastName: "Кузьменко",
      photoData: КузьменкоИгорь,
      terDivisionName: "СРБ",
      placeInRating: 1,
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "19",
      isMarked: false,
      firstName: "Алёна",
      lastName: "Берстенева",
      photoData: БерстеневаАлена,
      terDivisionName: "СИБ",
      placeInRating: 2,
      crystalsEarned: 119,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "3",
      isMarked: false,
      firstName: "Руфина",
      lastName: "Черняк",
      photoData: "",
      terDivisionName: "ББ",
      placeInRating: 3,
      crystalsEarned: 115,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "28",
      isMarked: false,
      firstName: "Наталья",
      lastName: "Дурова",
      photoData: ДуроваНаталья,
      terDivisionName: "ЦЧБ",
      placeInRating: 4,
      crystalsEarned: 114,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "14",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Орлова",
      photoData: ОрловаЮлия,
      terDivisionName: "ПБ",
      placeInRating: 5,
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
  ],
};
export const newsRatingTERB = {
  heading: "Игорь Кузьменко из СРБ на 1 месте!",
  usersPosition: "Вы на 1 из 3 месте",
  leaders: [
    {
      employeeNumber: "22",
      firstName: "Игорь",
      lastName: "Кузьменко",
      photoData: КузьменкоИгорь,
      terDivisionName: "СРБ",
      placeInRating: 1,
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      employeeNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 2,
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      employeeNumber: "23",
      isMarked: false,
      firstName: "Мария",
      lastName: "Тихомирова",
      photoData: ТихомироваМария,
      terDivisionName: "СРБ",
      placeInRating: 3,
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
  ],
};

export const newsRatingGOSB = {
  heading: "Игорь Кузьменко из СРБ на 1 месте!",
  usersPosition: "Вы на 1 из 1 месте",
  leaders: [
    {
      employeeNumber: "22",
      firstName: "Игорь",
      lastName: "Кузьменко",
      photoData: КузьменкоИгорь,
      terDivisionName: "СРБ",
      placeInRating: 1,
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
  ],
};

export const newsRating = {
  heading: "Анна Петровская из СБ на 1 месте!",
  usersPosition: "Вы на 12 из 1240 месте",
  leaders: [
    {
      employeeNumber: "010122",
      firstName: "Илья",
      lastName: "Герасимчук",
      photoData: "URL_in_Base64",
      terDivisionName: "ЦБ",
      placeInRating: 1,
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
  ],
};
