import АдиевРашид from "../assets/images/Адиев Рашид Абусат оглы.jpeg";
import БерстеневаАлена from "../assets/images/Берстенева Алена Викторовна.jpeg";
import БобокАлександр from "../assets/images/Бобок Александр Юрьевич.jpeg";
import БорбликМихаил from "../assets/images/Борблик Михаил Анатольевич.jpeg";
import ДмитриеваВероника from "../assets/images/Дмитриева Вероника Алексеевна.jpeg";
import ДуроваНаталья from "../assets/images/Дурова Наталья Юрьевна.jpeg";
import ЖаглинаЖанна from "../assets/images/Жаглина Жанна Маратовна.jpeg";
import КарагодинаМария from "../assets/images/Карагодина Мария Анатольевна.jpeg";
import КирееваЮлия from "../assets/images/Киреева Юлия Сергеевна.jpeg";
import КодоловаЕлена from "../assets/images/Кодолова Елена Аркадьевна.jpeg";
import КротковНиколай from "../assets/images/Кротков Николай Андреевич.jpeg";
import ГайнРоман from "../assets/images/romanGayn.png";
import КунинаТатьяна from "../assets/images/Кунина Татьяна Сергеевна.jpeg";
import МитренкоАндрей from "../assets/images/Митренко Андрей Игоревич.jpeg";
import ОрловаЮлия from "../assets/images/Орлова Юлия Валериевна.jpeg";
import ПроскуринаЕлена from "../assets/images/Проскурина Елена Михайловна.jpeg";
import СавушкинаЭмма from "../assets/images/Савушкина Эмма Александровна.jpeg";
import СенотрусоваЮлия from "../assets/images/Сенотрусова Юлия Юрьевна.jpeg";
import СеркбаеваАлтын from "../assets/images/Серкбаева Алтын Суннатовна.jpeg";
import СорокинИлья from "../assets/images/Сорокин Илья Юрьевич.jpeg";
import ТихомироваМария from "../assets/images/Тихомирова Мария Алексеевна.jpeg";
import ТомсонЕкатерина from "../assets/images/Томсон Екатерина Андреевна.jpeg";
import ХасаншинаВенера from "../assets/images/Хасаншина Венера Хамитовна.jpeg";
import ЧернецВиктория from "../assets/images/Чернец Виктория Александровна.jpeg";
import ШаброваИрина from "../assets/images/Шаброва Ирина Сергеевна.jpeg";
import ШебановаОльга from "../assets/images/Шебанова Ольга Евгеньевна.jpeg";
import МакаровПавел from "../assets/images/Макаров Павел Сергеевич.jpeg";

export const ratingList = {
  contestants: "1243 участника",
  leaders: [
    {
      profileNumber: "22",
      isMarked: true,
      firstName: "Роман",
      lastName: "Гайн",
      photoData: ГайнРоман,
      terDivisionName: "СРБ",
      placeInRating: 1,
      crystalsEarned: 120,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "19",
      isMarked: false,
      firstName: "Алёна",
      lastName: "Берстенева",
      photoData: БерстеневаАлена,
      terDivisionName: "СИБ",
      placeInRating: 2,
      crystalsEarned: 119,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "3",
      isMarked: false,
      firstName: "Руфина",
      lastName: "Черняк",
      photoData: "",
      terDivisionName: "ББ",
      placeInRating: 3,
      crystalsEarned: 115,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "28",
      isMarked: false,
      firstName: "Наталья",
      lastName: "Дурова",
      photoData: ДуроваНаталья,
      terDivisionName: "ЦЧБ",
      placeInRating: 4,
      crystalsEarned: 114,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "14",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Орлова",
      photoData: ОрловаЮлия,
      terDivisionName: "ПБ",
      placeInRating: 5,
      crystalsEarned: 112,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "25",
      isMarked: false,
      firstName: "Алтын",
      lastName: "Серкбаева",
      photoData: СеркбаеваАлтын,
      terDivisionName: "УБ",
      placeInRating: 6,
      crystalsEarned: 108,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "32",
      isMarked: false,
      firstName: "Михаил",
      lastName: "Борблик",
      photoData: БорбликМихаил,
      terDivisionName: "ЮЗБ",
      placeInRating: 7,
      crystalsEarned: 100,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "18",
      isMarked: false,
      firstName: "Эмма",
      lastName: "Савушкина",
      photoData: СавушкинаЭмма,
      terDivisionName: "СЗБ",
      placeInRating: 8,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "13",
      isMarked: false,
      firstName: "Мария",
      lastName: "Карагодина",
      photoData: КарагодинаМария,
      terDivisionName: "СИБ",
      placeInRating: 9,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "1",
      isMarked: false,
      firstName: "Павел",
      lastName: "Макаров",
      photoData: МакаровПавел,
      terDivisionName: "ББ",
      placeInRating: 10,
      crystalsEarned: 94,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "21",
      isMarked: false,
      firstName: "Екатерина",
      lastName: "Томсон",
      photoData: ТомсонЕкатерина,
      terDivisionName: "СИБ",
      placeInRating: 11,
      crystalsEarned: 93,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 12,
      crystalsEarned: 87,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "15",
      isMarked: false,
      firstName: "Татьяна",
      lastName: "Кунина",
      photoData: КунинаТатьяна,
      terDivisionName: "ПБ",
      placeInRating: 13,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "8",
      isMarked: false,
      firstName: "Илья",
      lastName: "Сорокин",
      photoData: СорокинИлья,
      terDivisionName: "ДВБ",
      placeInRating: 14,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "2",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ББ",
      placeInRating: 15,
      crystalsEarned: 84,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "26",
      isMarked: false,
      firstName: "Николай",
      lastName: "Кротков",
      photoData: КротковНиколай,
      terDivisionName: "УБ",
      placeInRating: 16,
      crystalsEarned: 83,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "33",
      isMarked: false,
      firstName: "Виктория",
      lastName: "Чернец",
      photoData: ЧернецВиктория,
      terDivisionName: "ЮЗБ",
      placeInRating: 17,
      crystalsEarned: 81,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "16",
      isMarked: false,
      firstName: "Александр",
      lastName: "Захаров",
      photoData: "",
      terDivisionName: "СЗБ",
      placeInRating: 18,
      crystalsEarned: 76,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "29",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Киреева",
      photoData: КирееваЮлия,
      terDivisionName: "ЦЧБ",
      placeInRating: 19,
      crystalsEarned: 76,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "5",
      isMarked: false,
      firstName: "Венера",
      lastName: "Хасаншина",
      photoData: ХасаншинаВенера,
      terDivisionName: "ВВБ",
      placeInRating: 20,
      crystalsEarned: 75,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "30",
      isMarked: false,
      firstName: "Жанна",
      lastName: "Жаглина",
      photoData: ЖаглинаЖанна,
      terDivisionName: "ЦЧБ",
      placeInRating: 21,
      crystalsEarned: 66,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "4",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ВВБ",
      placeInRating: 22,
      crystalsEarned: 62,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "9",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Сенотрусова",
      photoData: СенотрусоваЮлия,
      terDivisionName: "ДВБ",
      placeInRating: 23,
      crystalsEarned: 62,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "10",
      isMarked: false,
      firstName: "Вероника",
      lastName: "Дмитриева",
      photoData: ДмитриеваВероника,
      terDivisionName: "МБ",
      placeInRating: 24,
      crystalsEarned: 61,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "11",
      isMarked: false,
      firstName: "Ярослав",
      lastName: "Митосев",
      photoData: "",
      terDivisionName: "МБ",
      placeInRating: 25,
      crystalsEarned: 55,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "31",
      isMarked: false,
      firstName: "Ольга",
      lastName: "Шебанова",
      photoData: ШебановаОльга,
      terDivisionName: "ЮЗБ",
      placeInRating: 26,
      crystalsEarned: 48,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "17",
      isMarked: false,
      firstName: "Марина",
      lastName: "Сорокина",
      photoData: "",
      terDivisionName: "СЗБ",
      placeInRating: 27,
      crystalsEarned: 48,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "6",
      isMarked: false,
      firstName: "Елена",
      lastName: "Кодолова",
      photoData: КодоловаЕлена,
      terDivisionName: "ВВБ",
      placeInRating: 28,
      crystalsEarned: 43,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "7",
      isMarked: false,
      firstName: "Андрей",
      lastName: "Митренко",
      photoData: МитренкоАндрей,
      terDivisionName: "ДВБ",
      placeInRating: 29,
      crystalsEarned: 42,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "27",
      isMarked: false,
      firstName: "Мария",
      lastName: "Брусницына",
      photoData: "",
      terDivisionName: "УБ",
      placeInRating: 30,
      crystalsEarned: 42,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "20",
      isMarked: false,
      firstName: "Рашид",
      lastName: "Адиев",
      photoData: АдиевРашид,
      terDivisionName: "СИБ",
      placeInRating: 31,
      crystalsEarned: 40,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "23",
      isMarked: false,
      firstName: "Мария",
      lastName: "Тихомирова",
      photoData: ТихомироваМария,
      terDivisionName: "СРБ",
      placeInRating: 32,
      crystalsEarned: 25,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "12",
      isMarked: false,
      firstName: "Александр",
      lastName: "Бобок",
      photoData: БобокАлександр,
      terDivisionName: "МБ",
      placeInRating: 33,
      crystalsEarned: 11,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
  ],
};

export const ratingListQuarter = {
  contestants: "33 участника",
  leaders: [
    {
      profileNumber: "22",
      isMarked: true,
      firstName: "Роман",
      lastName: "Гайн",
      photoData: ГайнРоман,
      terDivisionName: "СРБ",
      placeInRating: 7,
      crystalsEarned: 35,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "19",
      isMarked: false,
      firstName: "Алёна",
      lastName: "Берстенева",
      photoData: БерстеневаАлена,
      terDivisionName: "СИБ",
      placeInRating: 29,
      crystalsEarned: 2,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "3",
      isMarked: false,
      firstName: "Руфина",
      lastName: "Черняк",
      photoData: "",
      terDivisionName: "ББ",
      placeInRating: 9,
      crystalsEarned: 27,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "28",
      isMarked: false,
      firstName: "Наталья",
      lastName: "Дурова",
      photoData: ДуроваНаталья,
      terDivisionName: "ЦЧБ",
      placeInRating: 4,
      crystalsEarned: 43,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "14",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Орлова",
      photoData: ОрловаЮлия,
      terDivisionName: "ПБ",
      placeInRating: 23,
      crystalsEarned: 9,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "25",
      isMarked: false,
      firstName: "Алтын",
      lastName: "Серкбаева",
      photoData: СеркбаеваАлтын,
      terDivisionName: "УБ",
      placeInRating: 5,
      crystalsEarned: 40,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "32",
      isMarked: false,
      firstName: "Михаил",
      lastName: "Борблик",
      photoData: БорбликМихаил,
      terDivisionName: "ЮЗБ",
      placeInRating: 21,
      crystalsEarned: 11,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "18",
      isMarked: false,
      firstName: "Эмма",
      lastName: "Савушкина",
      photoData: СавушкинаЭмма,
      terDivisionName: "СЗБ",
      placeInRating: 1,
      crystalsEarned: 55,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "13",
      isMarked: false,
      firstName: "Мария",
      lastName: "Карагодина",
      photoData: КарагодинаМария,
      terDivisionName: "СИБ",
      placeInRating: 17,
      crystalsEarned: 15,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "1",
      isMarked: false,
      firstName: "Павел",
      lastName: "Макаров",
      photoData: МакаровПавел,
      terDivisionName: "ББ",
      placeInRating: 31,
      crystalsEarned: 1,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "21",
      isMarked: false,
      firstName: "Екатерина",
      lastName: "Томсон",
      photoData: ТомсонЕкатерина,
      terDivisionName: "СИБ",
      placeInRating: 10,
      crystalsEarned: 26,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 11,
      crystalsEarned: 26,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "15",
      isMarked: false,
      firstName: "Татьяна",
      lastName: "Кунина",
      photoData: КунинаТатьяна,
      terDivisionName: "ПБ",
      placeInRating: 26,
      crystalsEarned: 6,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "8",
      isMarked: false,
      firstName: "Илья",
      lastName: "Сорокин",
      photoData: СорокинИлья,
      terDivisionName: "ДВБ",
      placeInRating: 32,
      crystalsEarned: 1,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "2",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ББ",
      placeInRating: 19,
      crystalsEarned: 13,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "26",
      isMarked: false,
      firstName: "Николай",
      lastName: "Кротков",
      photoData: КротковНиколай,
      terDivisionName: "УБ",
      placeInRating: 15,
      crystalsEarned: 16,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "33",
      isMarked: false,
      firstName: "Виктория",
      lastName: "Чернец",
      photoData: ЧернецВиктория,
      terDivisionName: "ЮЗБ",
      placeInRating: 2,
      crystalsEarned: 50,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "16",
      isMarked: false,
      firstName: "Александр",
      lastName: "Захаров",
      photoData: "",
      terDivisionName: "СЗБ",
      placeInRating: 13,
      crystalsEarned: 23,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "29",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Киреева",
      photoData: КирееваЮлия,
      terDivisionName: "ЦЧБ",
      placeInRating: 6,
      crystalsEarned: 37,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "5",
      isMarked: false,
      firstName: "Венера",
      lastName: "Хасаншина",
      photoData: ХасаншинаВенера,
      terDivisionName: "ВВБ",
      placeInRating: 24,
      crystalsEarned: 8,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "30",
      isMarked: false,
      firstName: "Жанна",
      lastName: "Жаглина",
      photoData: ЖаглинаЖанна,
      terDivisionName: "ЦЧБ",
      placeInRating: 3,
      crystalsEarned: 46,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "4",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ВВБ",
      placeInRating: 20,
      crystalsEarned: 12,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "9",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Сенотрусова",
      photoData: СенотрусоваЮлия,
      terDivisionName: "ДВБ",
      placeInRating: 8,
      crystalsEarned: 28,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "10",
      isMarked: false,
      firstName: "Вероника",
      lastName: "Дмитриева",
      photoData: ДмитриеваВероника,
      terDivisionName: "МБ",
      placeInRating: 28,
      crystalsEarned: 4,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "11",
      isMarked: false,
      firstName: "Ярослав",
      lastName: "Митосев",
      photoData: "",
      terDivisionName: "МБ",
      placeInRating: 12,
      crystalsEarned: 25,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "31",
      isMarked: false,
      firstName: "Ольга",
      lastName: "Шебанова",
      photoData: ШебановаОльга,
      terDivisionName: "ЮЗБ",
      placeInRating: 18,
      crystalsEarned: 15,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "17",
      isMarked: false,
      firstName: "Марина",
      lastName: "Сорокина",
      photoData: "",
      terDivisionName: "СЗБ",
      placeInRating: 18,
      crystalsEarned: 15,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "6",
      isMarked: false,
      firstName: "Елена",
      lastName: "Кодолова",
      photoData: КодоловаЕлена,
      terDivisionName: "ВВБ",
      placeInRating: 25,
      crystalsEarned: 7,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "7",
      isMarked: false,
      firstName: "Андрей",
      lastName: "Митренко",
      photoData: МитренкоАндрей,
      terDivisionName: "ДВБ",
      placeInRating: 27,
      crystalsEarned: 5,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "27",
      isMarked: false,
      firstName: "Мария",
      lastName: "Брусницына",
      photoData: "",
      terDivisionName: "УБ",
      placeInRating: 14,
      crystalsEarned: 23,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "20",
      isMarked: false,
      firstName: "Рашид",
      lastName: "Адиев",
      photoData: АдиевРашид,
      terDivisionName: "СИБ",
      placeInRating: 22,
      crystalsEarned: 11,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "23",
      isMarked: false,
      firstName: "Мария",
      lastName: "Тихомирова",
      photoData: ТихомироваМария,
      terDivisionName: "СРБ",
      placeInRating: 33,
      crystalsEarned: 1,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "12",
      isMarked: false,
      firstName: "Александр",
      lastName: "Бобок",
      photoData: БобокАлександр,
      terDivisionName: "МБ",
      placeInRating: 30,
      crystalsEarned: 2,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
  ],
};

export const ratingListTB = {
  contestants: "152 участника",
  leaders: [
    {
      profileNumber: "22",
      isMarked: true,
      firstName: "Роман",
      lastName: "Гайн",
      photoData: ГайнРоман,
      terDivisionName: "СРБ",
      placeInRating: 1,
      crystalsEarned: 120,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 2,
      crystalsEarned: 87,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "23",
      isMarked: false,
      firstName: "Мария",
      lastName: "Тихомирова",
      photoData: ТихомироваМария,
      terDivisionName: "СРБ",
      placeInRating: 3,
      crystalsEarned: 25,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "28",
      isMarked: false,
      firstName: "Наталья",
      lastName: "Дурова",
      photoData: ДуроваНаталья,
      terDivisionName: "ЦЧБ",
      placeInRating: 4,
      crystalsEarned: 114,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "14",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Орлова",
      photoData: ОрловаЮлия,
      terDivisionName: "ПБ",
      placeInRating: 5,
      crystalsEarned: 112,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "25",
      isMarked: false,
      firstName: "Алтын",
      lastName: "Серкбаева",
      photoData: СеркбаеваАлтын,
      terDivisionName: "УБ",
      placeInRating: 6,
      crystalsEarned: 108,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "32",
      isMarked: false,
      firstName: "Михаил",
      lastName: "Борблик",
      photoData: БорбликМихаил,
      terDivisionName: "ЮЗБ",
      placeInRating: 7,
      crystalsEarned: 100,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "18",
      isMarked: false,
      firstName: "Эмма",
      lastName: "Савушкина",
      photoData: СавушкинаЭмма,
      terDivisionName: "СЗБ",
      placeInRating: 8,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "13",
      isMarked: false,
      firstName: "Мария",
      lastName: "Карагодина",
      photoData: КарагодинаМария,
      terDivisionName: "СИБ",
      placeInRating: 9,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "1",
      isMarked: false,
      firstName: "Павел",
      lastName: "Макаров",
      photoData: МакаровПавел,
      terDivisionName: "ББ",
      placeInRating: 10,
      crystalsEarned: 94,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "21",
      isMarked: false,
      firstName: "Екатерина",
      lastName: "Томсон",
      photoData: ТомсонЕкатерина,
      terDivisionName: "СИБ",
      placeInRating: 11,
      crystalsEarned: 93,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 12,
      crystalsEarned: 87,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "15",
      isMarked: false,
      firstName: "Татьяна",
      lastName: "Кунина",
      photoData: КунинаТатьяна,
      terDivisionName: "ПБ",
      placeInRating: 13,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "8",
      isMarked: false,
      firstName: "Илья",
      lastName: "Сорокин",
      photoData: СорокинИлья,
      terDivisionName: "ДВБ",
      placeInRating: 14,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "2",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ББ",
      placeInRating: 15,
      crystalsEarned: 84,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "26",
      isMarked: false,
      firstName: "Николай",
      lastName: "Кротков",
      photoData: КротковНиколай,
      terDivisionName: "УБ",
      placeInRating: 16,
      crystalsEarned: 83,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "33",
      isMarked: false,
      firstName: "Виктория",
      lastName: "Чернец",
      photoData: ЧернецВиктория,
      terDivisionName: "ЮЗБ",
      placeInRating: 17,
      crystalsEarned: 81,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "16",
      isMarked: false,
      firstName: "Александр",
      lastName: "Захаров",
      photoData: "",
      terDivisionName: "СЗБ",
      placeInRating: 18,
      crystalsEarned: 76,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "29",
      isMarked: false,
      firstName: "Юлия",
      lastName: "Киреева",
      photoData: КирееваЮлия,
      terDivisionName: "ЦЧБ",
      placeInRating: 19,
      crystalsEarned: 76,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "5",
      isMarked: false,
      firstName: "Венера",
      lastName: "Хасаншина",
      photoData: ХасаншинаВенера,
      terDivisionName: "ВВБ",
      placeInRating: 20,
      crystalsEarned: 75,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "30",
      isMarked: false,
      firstName: "Жанна",
      lastName: "Жаглина",
      photoData: ЖаглинаЖанна,
      terDivisionName: "ЦЧБ",
      placeInRating: 21,
      crystalsEarned: 66,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "4",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ВВБ",
      placeInRating: 22,
      crystalsEarned: 62,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
  ],
};

export const ratingListTBQuarter = {
  contestants: "3 участника",
  leaders: [
    {
      profileNumber: "22",
      isMarked: true,
      firstName: "Роман",
      lastName: "Гайн",
      photoData: ГайнРоман,
      terDivisionName: "СРБ",
      placeInRating: 1,
      crystalsEarned: 35,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 2,
      crystalsEarned: 26,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "23",
      isMarked: false,
      firstName: "Мария",
      lastName: "Тихомирова",
      photoData: ТихомироваМария,
      terDivisionName: "СРБ",
      placeInRating: 3,
      crystalsEarned: 1,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
  ],
};

export const ratingListGOSB = {
  contestants: "15 участников",
  leaders: [
    {
      profileNumber: "22",
      isMarked: true,
      firstName: "Роман",
      lastName: "Гайн",
      photoData: ГайнРоман,
      terDivisionName: "СРБ",
      placeInRating: 1,
      crystalsEarned: 120,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
    {
      profileNumber: "18",
      isMarked: false,
      firstName: "Эмма",
      lastName: "Савушкина",
      photoData: СавушкинаЭмма,
      terDivisionName: "СЗБ",
      placeInRating: 2,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "13",
      isMarked: false,
      firstName: "Мария",
      lastName: "Карагодина",
      photoData: КарагодинаМария,
      terDivisionName: "СИБ",
      placeInRating: 3,
      crystalsEarned: 98,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "1",
      isMarked: false,
      firstName: "Павел",
      lastName: "Макаров",
      photoData: МакаровПавел,
      terDivisionName: "ББ",
      placeInRating: 4,
      crystalsEarned: 94,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "21",
      isMarked: false,
      firstName: "Екатерина",
      lastName: "Томсон",
      photoData: ТомсонЕкатерина,
      terDivisionName: "СИБ",
      placeInRating: 5,
      crystalsEarned: 93,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "24",
      isMarked: false,
      firstName: "Ирина",
      lastName: "Шаброва",
      photoData: ШаброваИрина,
      terDivisionName: "СИБ",
      placeInRating: 6,
      crystalsEarned: 87,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "15",
      isMarked: false,
      firstName: "Татьяна",
      lastName: "Кунина",
      photoData: КунинаТатьяна,
      terDivisionName: "ПБ",
      placeInRating: 7,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "8",
      isMarked: false,
      firstName: "Илья",
      lastName: "Сорокин",
      photoData: СорокинИлья,
      terDivisionName: "ДВБ",
      placeInRating: 8,
      crystalsEarned: 85,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "2",
      isMarked: false,
      firstName: "Елена",
      lastName: "Проскурина",
      photoData: ПроскуринаЕлена,
      terDivisionName: "ББ",
      placeInRating: 9,
      crystalsEarned: 84,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "26",
      isMarked: false,
      firstName: "Николай",
      lastName: "Кротков",
      photoData: КротковНиколай,
      terDivisionName: "УБ",
      placeInRating: 10,
      crystalsEarned: 83,
      indicatorValue: "",
      colorCode: {
        primary: "orange-60",
        secondary: "orange-30",
      },
    },
    {
      profileNumber: "7",
      isMarked: false,
      firstName: "Андрей",
      lastName: "Митренко",
      photoData: МитренкоАндрей,
      terDivisionName: "ДВБ",
      placeInRating: 11,
      crystalsEarned: 42,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "27",
      isMarked: false,
      firstName: "Мария",
      lastName: "Брусницына",
      photoData: "",
      terDivisionName: "УБ",
      placeInRating: 12,
      crystalsEarned: 42,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "20",
      isMarked: false,
      firstName: "Рашид",
      lastName: "Адиев",
      photoData: АдиевРашид,
      terDivisionName: "СИБ",
      placeInRating: 13,
      crystalsEarned: 40,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "23",
      isMarked: false,
      firstName: "Мария",
      lastName: "Тихомирова",
      photoData: ТихомироваМария,
      terDivisionName: "СРБ",
      placeInRating: 14,
      crystalsEarned: 25,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
    {
      profileNumber: "12",
      isMarked: false,
      firstName: "Александр",
      lastName: "Бобок",
      photoData: БобокАлександр,
      terDivisionName: "МБ",
      placeInRating: 15,
      crystalsEarned: 11,
      indicatorValue: "",
      colorCode: {
        primary: "light-green-30",
        secondary: "light-green-20",
      },
    },
  ],
};

export const ratingListGOSBQuarter = {
  contestants: "1 участник",
  leaders: [
    {
      profileNumber: "22",
      isMarked: true,
      firstName: "Роман",
      lastName: "Гайн",
      photoData: ГайнРоман,
      terDivisionName: "СРБ",
      placeInRating: 1,
      crystalsEarned: 35,
      indicatorValue: "",
      colorCode: {
        primary: "blue-60",
        secondary: "blue-30",
      },
    },
  ],
};
